### ISSUE TITLE
feature missing: inject requirements

### ISSUE THREAD

**Issue by prismv** [bulletmark/pipxu#12]
Thank you for this nice project. I had just found out about uv and pipxu. It's great to get speedy pipx commands.

Suppose that `pipxu install west` was performed, it would be great to be able to call e.g.:

`pipxu inject west -r requirements.txt`.

This is possible with pipx, but currently not implemented in pipxu.

Btw. this seems to be a workaround:

`pipxu runpip west -- install -r requirements.txt`

**Comment by bulletmark** [comment]
Note the first paragraph I said [here](https://github.com/bulletmark/pipxu/issues/5#issuecomment-2100536956) which is exactly what I would reply here also. Sorry, I don't want to complicate the implementation by adding obscure combinations of options particularly when, as you point out, that operation can be done almost as trivially using `runpip`.

**Comment by bulletmark** [comment]
BTW, you could probably also just type `pipxu inject west $(cat requirements.txt)`.

**Comment by prismv** [comment]
> BTW, you could probably also just type `pipxu inject west $(cat requirements.txt)`.

Thank you for your feedback. 

In my given case requirement has consecutive requirements-* entries. So the most simple variant with cat might not work or only with multiple calls.

FYI I also tried uv cli commands. This was working out of the box.
