### ISSUE TITLE
pipxu cannot find uv package

### ISSUE THREAD

**Issue by ArneBachmannDLR** [bulletmark/pipxu#4]
In an elevated shell I install pipx via `python -m pip install pipx`.

In a demoted shell I install pipxu via `pipx install pipxu`:

```cmd
>pipx install pipxu
  installed package pipxu 1.15, installed using Python 3.10.6
  These apps are now globally available
    - pipxu-bootstrap
    - pipxu.exe
done! ✨ 🌟 ✨
```

Then I run
```cmd
>pipxu list
Error: uv program must be installed, and in your PATH or specified with --uv option.
```

It seems like pipxu executes uv via command line instead of using its library API, and the dependency on uv is not installed automatically into the pipx environment.
Any ideas how to resolve that?

I then tried installing pipxu into the base/global conda environment, but the same error still appears. I guess the dependency on uv is not declared in the pipxu package.

*Edit:* Upon further consultation of README, it seems uv cannot be installed via pip at all???

**Comment by ArneBachmann** [comment]
I tried
```
pipx install pipxu
pipx inject pipxu uv
```
but that failed.
Installing `uv` into a different pipx environment seems to work flawlessly, so that's resolved :-)

**Comment by bulletmark** [comment]
@ArneBachmann are you using Linux, Mac, or Windows?

**Comment by ArneBachmannDLR** [comment]
On MX Linux that worked. On Windows 10 22H2:

```
H:\>pipxu install youtube-dl
>>> Running uv venv -p python -q 'C:\Users\...\AppData\Local\pipxu\venvs\1'
thread 'main' panicked at crates\uv-fs\src\path.rs:10:10:
The current directory must exist: Os { code: 5, kind: PermissionDenied, message: "Zugriff verweigert" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: failed to create C:\Users\...\AppData\Local\pipxu\venvs\1 for youtube-dl.
```

**Comment by bulletmark** [comment]
That error message is directly from `uv`. Not sure what "Zugriff verweigert" means but seems to be some permission error.

So, regarding this actual issue, since you were using Linux why didn't you just follow the normal instructions to install `uv` and then `pipxu` as in the README here?

**Comment by ArneBachmannDLR** [comment]
Well looking at https://github.com/astral-sh/uv the installation should work via `pipx install uv`, which it did on Linux and Windows.

But when running the code, I get access denied errors. I tried to grant access to all users, but still same error... Not sure what's going on, just reporting it here for reference.

```
D:\forks\HACE\autocook>pipxu install youtube-dl
Purging stray "C:\Users\...\AppData\Local\pipxu\venvs\1"
Traceback (most recent call last):
  File "C:\ProgramData\mambaforge_22.9.0.2\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\mambaforge_22.9.0.2\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\mambaforge_22.9.0.2\Scripts\pipxu.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\mambaforge_22.9.0.2\lib\site-packages\pipxu\pipxu.py", line 181, in main
    utils.purge_old_files(args)
  File "C:\ProgramData\mambaforge_22.9.0.2\lib\site-packages\pipxu\utils.py", line 282, in purge_old_files
    _rm_path(vdir)
  File "C:\ProgramData\mambaforge_22.9.0.2\lib\site-packages\pipxu\utils.py", line 261, in _rm_path
    path.unlink()
  File "C:\ProgramData\mambaforge_22.9.0.2\lib\pathlib.py", line 1206, in unlink
    self._accessor.unlink(self)
PermissionError: [WinError 5] Zugriff verweigert: 'C:\\Users\\...\\AppData\\Local\\pipxu\\venvs\\1'
```

**Comment by bulletmark** [comment]
Sorry, I don't know Windows at all and have never used it. Can you clarify - are those `...` characters actually being printed verbatim like that, or are you editing that output to hide some personal details, e.g. your user name?

There is also something inconsistent here. The output just above purges the `pipxu/venv/1` directory in `C:\Users\...\AppData\Local` but you said earlier that the `pipxu` directory was not there. Were you incorrect earlier?

**Comment by ArneBachmannDLR** [comment]
Yes I redacted my user name. And before, the pipxu folder was missing, after fiddling around with pipx inside and outside virtual environments it does exist now, yet cannot be removed, despite setting all access rights. Pretty messy now, can be a relict of having installed Mambaforge as an admin, but acting as a user with conda environments (as intended). If you want, I can remove it completely and start over in a more formal fashion, but no worries if that is ouside your scope.

**Comment by bulletmark** [comment]
No, this issue is about not being able to install `uv` but it seems you have worked that out. Your second issue is about Windows permissions/access which is not relevant to the issue here and not something I can deal with anyway I guess. So it is ok if I close this bug?

**Comment by ArneBachmannDLR** [comment]
Of course, it's your jam :-D I will keep testing once in a while
